### ISSUE TITLE
Revise sketch download logic

### ISSUE THREAD

**Issue by codeanticode** [remixlab/shaderbase#14]
Should work in one of the following ways:

1) If the PDE is empty, load sketch into current window
2) If PDE is not empty, create new instance holding new sketch

OR

1) If the PDE is empty, load sketch into current window
2) If PDE is not empty, check if current sketch is saved or not
3) If it is saved, just restart PDE to show new sketch
4) If it is not saved, ask if the user wants to save it or not.

**Comment by anfgomezmo** [comment]
The logic used was the option 1. If the sketch is empty a shader is loaded there, if not a new skecth is created and the tool adds the shader there.
